# Numpy Array Attributes

* **ndim, shape, size, dtype**

In [5]:
import numpy as np

In [6]:
arr1 = np.random.randint(10, size = 10)
print(arr1)

[8 7 7 6 6 9 1 1 8 8]


In [7]:
print(arr1.ndim, end = ", ")
print(arr1.shape, end = ", ")
print(arr1.size, end = ", ")
print(arr1.dtype, end = ".\n")

1, (10,), 10, int32.


In [8]:
arr2 = np.random.randint(10, size = (3, 5))
print(arr2)

[[3 2 6 9 9]
 [7 8 7 7 6]
 [7 9 6 1 8]]


In [9]:
print(arr2.ndim, end = ", ")
print(arr2.shape, end = ", ")
print(arr2.size, end = ", ")
print(arr2.dtype, end = ".\n")

2, (3, 5), 15, int32.


# Reshaping

In [10]:
arr1 = np.arange(1, 10)
arr2 = arr1.reshape((3, 3))
print(arr1)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr3 = arr1.reshape((1,9))
print(arr1)
print(arr3)
print(arr3.ndim)

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
2


# Concatenation

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1, arr2])

In [13]:
print(arr3)

[1 2 3 4 5 6]


In [14]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [15]:
arr2 = np.concatenate([arr1, arr1], axis = 0) #default axis value
arr3 = np.concatenate([arr1, arr1], axis = 1)

In [16]:
print(arr2, end = "\n\n")
print(arr3)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


# Splitting

In [17]:
arr1 = np.array([1, 2, 3, 100, 101, 3, 2, 1])
arr2, arr3, arr4 = np.split(arr1, [3, 5])
print(arr2, ", ", arr3, ", ", arr4)

[1 2 3] ,  [100 101] ,  [3 2 1]


In [18]:
arr1 = np.arange(9).reshape(3, 3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
arr2, arr3 = np.vsplit(arr1, [2])
print(arr2, "\n\n", arr3)

[[0 1 2]
 [3 4 5]] 

 [[6 7 8]]


In [20]:
arr2, arr3 = np.hsplit(arr1, [2])
print(arr2, "\n\n", arr3)

[[0 1]
 [3 4]
 [6 7]] 

 [[2]
 [5]
 [8]]


# Sorting

In [21]:
arr1 = np.array([2, 1, 9, 3, 4])
print(np.sort(arr1))
print(arr1)

[1 2 3 4 9]
[2 1 9 3 4]


In [22]:
print(arr1)
arr1.sort()
print(arr1)

[2 1 9 3 4]
[1 2 3 4 9]


In [23]:
arr1 = np.random.normal(10, 5, (3,3))
print(arr1)

[[ 5.49351994  8.34850664  9.52001139]
 [ 7.98543323  9.11198698 14.19966204]
 [12.40546705  5.5652035  13.53582154]]


In [24]:
print(np.sort(arr1, axis = 0), end = "\n\n")
print(np.sort(arr1, axis = 1))

[[ 5.49351994  5.5652035   9.52001139]
 [ 7.98543323  8.34850664 13.53582154]
 [12.40546705  9.11198698 14.19966204]]

[[ 5.49351994  8.34850664  9.52001139]
 [ 7.98543323  9.11198698 14.19966204]
 [ 5.5652035  12.40546705 13.53582154]]


# Index

In [25]:
arr1 = np.random.randint(10, size = 10)
print(arr1)

[3 5 0 0 8 2 9 0 0 5]


In [32]:
print(arr1[0], arr1[-1], sep = ", ")

3, 5


In [33]:
arr1 = np.random.randint(10, size = (3, 4))
print(arr1)

[[8 3 9 4]
 [6 0 3 0]
 [2 0 0 0]]


In [38]:
print(arr1[0][0], arr1[-1][-1], sep = ", ")

8, 0


In [47]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1[0::2])
print(arr1[1::2])

[0 2 4 6 8]
[1 3 5 7 9]


# Slicing

In [48]:
arr1 = np.random.randint(10, size = (5, 5))
print(arr1)

[[5 6 0 9 3]
 [8 6 4 4 5]
 [5 1 8 2 8]
 [7 9 5 9 8]
 [0 9 8 6 0]]


In [50]:
print(arr1[:, 0])

[5 8 5 7 0]


In [51]:
print(arr1[:, 2])

[0 4 8 5 8]


In [52]:
print(arr1[0,:])

[5 6 0 9 3]


In [53]:
print(arr1[3, :])

[7 9 5 9 8]


In [59]:
print(arr1[1:3, 1:3], end = "\n\n")
print(arr1[:2, :3])

[[6 4]
 [1 8]]

[[5 6 0]
 [8 6 4]]


# Subarray

In [60]:
arr1 = np.random.randint(10, size = (5, 5))
print(arr1)

[[4 0 2 1 6]
 [3 8 3 7 6]
 [1 1 3 6 0]
 [0 0 6 3 3]
 [8 7 3 9 3]]


In [61]:
subarray = arr1[:3, :2]
print(subarray)

[[4 0]
 [3 8]
 [1 1]]


In [62]:
subarray[0,0] = 999
subarray[2,0] = 8888
print(subarray)

[[ 999    0]
 [   3    8]
 [8888    1]]


In [63]:
print(arr1)

[[ 999    0    2    1    6]
 [   3    8    3    7    6]
 [8888    1    3    6    0]
 [   0    0    6    3    3]
 [   8    7    3    9    3]]


In [64]:
arr1 = np.random.randint(10, size = (5, 5))
print(arr1)

[[8 7 6 3 8]
 [4 3 1 8 1]
 [1 3 2 0 3]
 [6 7 2 5 5]
 [6 7 5 3 5]]


In [65]:
subarray = arr1[:3, :2].copy()
print(subarray)

[[8 7]
 [4 3]
 [1 3]]


In [66]:
subarray[0,0] = 999
subarray[2,0] = 8888
print(subarray)

[[ 999    7]
 [   4    3]
 [8888    3]]


In [67]:
print(arr1)

[[8 7 6 3 8]
 [4 3 1 8 1]
 [1 3 2 0 3]
 [6 7 2 5 5]
 [6 7 5 3 5]]


# Fancy Index

In [72]:
arr1 = np.arange(20)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [73]:
indices = [1, 12, 15, 17, 19]
print(arr1[indices])

[ 1 12 15 17 19]


In [74]:
arr1 = np.arange(9).reshape((3,3))
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [75]:
row = [0, 2]
col = [1, 2]
print(arr1[row, col])

[1 8]


In [76]:
print(arr1[1, [1, 2]])

[4 5]


In [77]:
print(arr1[1:, [1, 2]])

[[4 5]
 [7 8]]


# Item Conditions

In [78]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1 < 3)

[ True  True False False False]


In [80]:
print(arr1[arr1 < 3])

[ True  True False False False]


In [83]:
print(arr1[arr1 > 3])

[4 5]


In [82]:
print(arr1[arr1 >= 3])

[3 4 5]


In [84]:
print(arr1[arr1 == 3])

[3]


In [85]:
print(arr1[arr1 != 3])

[1 2 4 5]


In [87]:
print(arr1**2)

[ 1  4  9 16 25]


# ufunc

In [88]:
print(arr1 % 2)
print(np.mod(arr1, 2))

[1 0 1 0 1]
[1 0 1 0 1]


In [90]:
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [92]:
print(np.log2(arr1))

[0.         1.         1.5849625  2.         2.32192809]


In [93]:
print(np.log10(arr1))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]


**5x0 + x1 = 12**  
**x0 + 3x1 = 10**

In [96]:
arr1 = np.array([[5, 1], [1, 3]])
arr2 = np.array([12, 10])

In [98]:
x = np.linalg.solve(arr1, arr2)
print(x)

[1.85714286 2.71428571]
